---
default_set: 'ubuntu-server-12042-x64'
sets:
  'centos-58-x64':
    nodes:
      'main.foo.vm':
        prefab: 'centos-58-x64'
  'centos-59-x64':
    nodes:
      'main.foo.vm':
        prefab: 'centos-59-x64'
  'centos-63-x64':
    nodes:
      'main.foo.vm':
        prefab: 'centos-63-x64'
  'centos-64-x64':
    nodes:
      'main.foo.vm':
        prefab: 'centos-64-x64'
  'ubuntu-server-10044-x64':
    nodes:
      "main.foo.vm":
        prefab: 'ubuntu-server-10044-x64'
  'ubuntu-server-12042-x64':
    nodes:
      "main.foo.vm":
        prefab: 'ubuntu-server-12042-x64'
